### ISSUE TITLE
confusion... maybe explain it in documentation?

### ISSUE THREAD

**Issue by einthusan** [jawher/mow.cli#6]
```
	gocdn.Command(`kill`, `terminate the ssh connection`, func(cmd *cli.Cmd) {

		_all := cmd.BoolOpt(`a all`, false, `kill all ssh connections`)

		fmt.Println(*_all)
		cmd.Action = func() {
			fmt.Println(*_all)
		}
	})
```
```
false
true
```

What exactly is the reason why the flag is only available within Action? and why Action command at all?

**Comment by jawher** [comment]
Right at the end of the Commands section in mow.cli's readme file, there's [this side-note](https://github.com/jawher/mow.cli#commands):

> As a side-note: it may seem a bit weird the way mow.cli uses a function to initialize a command instead of just returning the command struct.

> The motivation behind this choice is scoping: as with the standard flag package, adding an option or an argument returns a pointer to a value which will be populated when the app is run.

> Since you'll want to store these pointers in variables, and to avoid having dozens of them in the same scope (the main func for example or as global variables), mow.cli's API was specifically tailored to take a func parameter (called CmdInitializer) which accepts the command struct.

> This way, the command specific variables scope is limited to this function.

In your case, the function you pass to `gocdn.Command("kill" ...` serves to configure the `kill` command, i.e.:

* Declare the options and arguments it accepts
* Optionally define the spec string
* Optionally define the code to run when this command is called from the command line (by setting the `Action` field)

Inside this initialization function, the call arguments are not parsed yet: the CLI app is still being constructed.  That's why the options and arguments values are not available.

When you later call `app.Parse(os.Args)`, that's when the call arguments get parsed and the options and positional arguments pointers get their values set. mow.cli then calls the Action of the matching command and that's where you can safely use the `_all` variable.

I'm working on setting up a documentation site that goes beyond a readme and the godoc. Stay tuned.

**Comment by einthusan** [comment]
Okay i understand, I've had great success with your package, so thanks for that. 

It's just that I spent an hour trying to figure out WHY it was misbehaving and the reason behind it. It now makes sense. I suggest that the new documentation you are writing clearly says something along the lines of... "NOTE: FLAG values are only available within the ACTION function"
