### ISSUE TITLE
howto: optional longOpt before a repetition

### ISSUE THREAD

**Issue by wmark** [jawher/mow.cli#8]
For a reverse proxy I've created intuitively a spec like this:

```go
func record(cmd *cli.Cmd) {
	cmd.Spec = "[--listen] HOSTNAME..."
	var (
		listenOn  = cmd.String(cli.StringArg{Name: "listen", Value: "127.0.0.7:7000", EnvVar: "LISTEN"})
		hostnames = cmd.StringsArg("HOSTNAME", nil, "")
	)

	cmd.Action = func() {
		log.Printf("Ignored for now: %v", hostnames)
		startReverseProxy(listenOn)
	}
}
```

… with the application *record* being invoked like this:
```bash
recorder record www.target.tld
recorder record www.target.tld example2.com
recorder record --listen=8.8.8.8:2700 www.target.tld example2.com example3.com
```

Well, the above spec leads to this error:
```
panic: Parse error at position 9:
[--listen] HOSTNAME...
         ^ Undeclared option --listen
```

* What would be the correct *cmd.Spec*?
* How can I introduce option ```--listen-on``` (including the dash)?
* ```cmd.Spec = "[--listen] HOSTNAME... DIRECTORY```?

**Comment by jawher** [comment]
You spec string is valid. The problem occurs because you declared the `listen` option as an argument and not as an option:

```go
listenOn  = cmd.String(cli.StringArg{Name: "listen", Value: "127.0.0.7:7000", EnvVar: "LISTEN"})
```

You should use `cli.StringOpt` instead of `cli.StringArg` which should fix the problem.

As a side note, mow,cli shares a part of the blame here: it should reject an argument declaration when the name is not in all caps.

**Comment by wmark** [comment]
Wunderbar! Merci beaucoup.

I've confused 'arguments' and 'options'.
